### ISSUE TITLE
Hacktoberfest 2020

### ISSUE THREAD

**Issue by ashiishme** [ashiishme/open-source-enthusiasts#1]
### Hacktoberfest 2020

Anyone interested to send your PR are very welcome. Add your name with the GitHub profile link and you are done.

Please check [Contribution](https://github.com/ashiishme/open-source-enthusiasts#contributing) section.

Also, do not re-order the list. If you have any confusion, feel free to ask in comment.

Note:  This project uses `main` as a base branch. Don't get confused with `master`.

**Comment by TheBinitGhimire** [comment]
Great Initiation, @ashiishme! I will suggest my friends to contribute to this repository.

**Comment by ashiishme** [comment]
Sure.
