### ISSUE TITLE
Showcase your personal profile - Hacktoberfest 2020

### ISSUE THREAD

**Issue by ashiishme** [ashiishme/open-source-enthusiasts#83]
Showcase your personal profile - Hacktoberfest 2020

Anyone interested to send your PR are very welcome. Please check [Contribution section](https://github.com/ashiishme/open-source-enthusiasts#contributing) & follow the instruction.

Please don't send PR regarding grammatical errors or typo fixes. Your PR must be based on contribution section or it will be marked as invalid.

Tip: If you want to quickly send a PR, download the `profile readme.md` file from your profile repository. Rename it with your username & send PR. 

If you have any confusion, feel free to ask in comment.

Note: This project uses main as a base branch. Don't get confused with master.

**Comment by aortiz24** [comment]
I would like to work on this! It's my first time at hacktoberfest!

**Comment by ashiishme** [comment]
@aortiz24  Yes please, just follow the contributing section and you will be able to send your first PR. Good luck. :champagne:

**Comment by rubenkharel** [comment]
Will it be counted as a valid PR of hacktoberfest?

**Comment by ashiishme** [comment]
It's up to Hacktoberfest team to decide so I am not sure but the repository will still be active. The main concept behind this is to showcase profile in one place.

**Comment by volt9801** [comment]
@ashiishme I made a PR, please review it.

**Comment by ashiishme** [comment]
Thanks everyone, I am closing this issue and hope everyone had an awesome open-source experience. :slightly_smiling_face:
